### ISSUE TITLE
[FEATURE| Creeper breeding!

### ISSUE THREAD

**Issue by T145** [T145/allthecreepers#12]
Currently I'm working on a system that will allow certain creepers to fall in love in the wild and breed! There will be certain types of creepers that will not naturally spawn, and can only be created through even more natural means. Now it depends on the creeper, but the player may be able to kick-start the process for some creepers if you can sneak up on them (beautiful irony, eh?).

What I want from you guys are some suggestions for creeper breeds! There are some that are special, but any creative input is valued! If there's a creeper that isn't added yet, throw it in! I may add it in v2.0!

Current breed types:
```
    NAPALM(null),
    STEAM(null),
    LAVA(null),
    SMOKE(null), // illusion

    FIRE(new HashMap<CreeperType, CreeperType>() {{
        put(FIRE, NAPALM);
        put(WATER, STEAM);
        put(EARTH, LAVA);
        put(AIR, SMOKE);
    }}),

    ICE(null),
    NATURE(null),
    STORM(null),

    WATER(new HashMap<CreeperType, CreeperType>() {{
        put(FIRE, STEAM);
        put(WATER, ICE);
        put(EARTH, NATURE);
        put(AIR, STORM);
    }}),

    EARTHQUAKE(null),
    DUST(null),

    EARTH(new HashMap<CreeperType, CreeperType>() {{
        put(FIRE, LAVA);
        put(WATER, NATURE);
        put(EARTH, EARTHQUAKE);
        put(AIR, DUST);
    }}),

    UPDRAFT(null),

    AIR(new HashMap<CreeperType, CreeperType>() {{
        put(FIRE, SMOKE);
        put(WATER, STORM);
        put(EARTH, DUST);
        put(AIR, UPDRAFT);
    }});
```

**Comment by DarkGuardsman** [comment]
Could add in some plant-based creepers that shower plant parts when they explode. Would have a texture that would match the plant type. So flower creeper would have yellow or red flowers. When it explodes it will shower down some random flowers based on the color and texture.
